version: '2.0'
services:
    app:
        build: .
        volumes:
            - '.:/go/src/snippets.page-backend'
        ports:
            - "8080:8080"
        working_dir: /go/src/snippets.page-backend
        #restart: always 
        depends_on:
            - mongo
    mongo:
        image: mongo:3.4
        container_name: "sp_storage"
        ports:
            - 27017:27017
        volumes:
            - ./data/db:/data/db